#Kotlin
kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx3072M
kotlin.incremental.native=true

#Gradle
org.gradle.jvmargs=-Xmx5g -XX:MaxMetaspaceSize=2g -Dfile.encoding=UTF-8
org.gradle.configuration-cache=false
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.daemon=true
org.gradle.console=plain
org.gradle.warning.mode=summary

#Android
android.nonTransitiveRClass=false
android.useAndroidX=true
android.enableJetifier=true
android.dependency.excludeLibraryComponentsFromConstraints=true

#kmp
cinterop.commonization=true
kotlin.mpp.enableCInteropCommonization=true
kotlin.mpp.enableCInteropCommonization.nowarn=true
kotlin.mpp.stability.nowarn=true
kotlin.native.ignoreDisabledTargets=true
kotlin.native.cacheKind=static
kotlin.native.cinterop.cache.enabled=true
kotlin.apple.xcodeCompatibility.nowarn=true
kotlin.apple.dependencies.actualization.enabled=true

#AGP8 -> AGP9
android.defaults.buildfeatures.resvalues=true
android.sdk.defaultTargetSdkToCompileSdkIfUnset=false
android.enableAppCompileTimeRClass=false
android.usesSdkInManifest.disallowed=false
android.uniquePackageNames=false
android.dependency.useConstraints=true
android.r8.strictFullModeForKeepRules=false
android.r8.optimizedResourceShrinking=false
android.builtInKotlin=false
android.newDsl=false
