package com.frame.basic.plugin

import org.gradle.api.Plugin
import org.gradle.api.Project
import org.gradle.nativeplatform.platform.internal.DefaultNativePlatform

/**
 * @Description: 聚合各 SDK 模块声明的 iOS 配置，生成给 Xcode Info.plist 使用的 xcconfig 文件。
 * @Author:         范俊
 * @CreateDate:     2026/07/03 11:56
 */
class IosConfigPlugin : Plugin<Project> {
    override fun apply(target: Project) {
        val extension = target.extensions.create("iosConfig", IosConfigExtension::class.java)
        val registry = target.rootProject.iosConfigRegistry()
        registry.add(target.path, extension)
        target.rootProject.configureIosConfigTask(registry)

        target.tasks.register("generateIosConfig") {
            group = "ios"
            description = "Generates iosConfig.xcconfig from all module iosConfig declarations."
            dependsOn(target.rootProject.tasks.named(IOS_CONFIG_TASK_NAME))
        }
    }
}

open class IosConfigExtension {
    private val fields = linkedMapOf<String, String>()

    fun field(name: String, value: String) {
        fields[name] = value
    }

    internal fun entries(): Map<String, String> = fields.toMap()
}

private const val IOS_CONFIG_TASK_NAME = "generateIosConfig"
private const val IOS_CONFIG_EXTENSION_NAME = "iosConfigRegistry"
private val isMac = DefaultNativePlatform.getCurrentOperatingSystem().isMacOsX

private open class IosConfigRegistry {
    private val extensions = linkedMapOf<String, IosConfigExtension>()

    fun add(modulePath: String, extension: IosConfigExtension) {
        extensions[modulePath] = extension
    }

    fun toXcconfigContent(): String {
        val fields = linkedMapOf<String, Pair<String, String>>()
        extensions.forEach { (modulePath, extension) ->
            extension.entries().forEach { (name, value) ->
                val previous = fields.put(name, modulePath to value)
                require(previous == null || previous.second == value) {
                    "Duplicate iOS plist key '$name' from ${previous?.first} and $modulePath."
                }
            }
        }

        return buildString {
            appendLine("// This file is automatically generated by Gradle. Do not edit manually.")
            fields.forEach { (name, moduleAndValue) ->
                appendLine("$name=${moduleAndValue.second.toXcconfigValue()}")
            }
        }
    }
}

private fun Project.iosConfigRegistry(): IosConfigRegistry {
    val existing = extensions.findByName(IOS_CONFIG_EXTENSION_NAME) as? IosConfigRegistry
    if (existing != null) return existing
    return extensions.create(IOS_CONFIG_EXTENSION_NAME, IosConfigRegistry::class.java)
}

private fun Project.configureIosConfigTask(registry: IosConfigRegistry) {
    if (tasks.findByName(IOS_CONFIG_TASK_NAME) != null) return

    val outputFile = file("iosApp/Configuration/iosConfig.xcconfig")
    fun syncConfig() {
        val newContent = registry.toXcconfigContent()
        if (!outputFile.exists() || outputFile.readText() != newContent) {
            outputFile.parentFile.mkdirs()
            outputFile.writeText(newContent)
            logger.lifecycle("${outputFile.name} updated successfully from iosConfig declarations")
        }
    }

    if (isMac) {
        gradle.projectsEvaluated {
            syncConfig()
        }
    }

    tasks.register(IOS_CONFIG_TASK_NAME) {
        group = "ios"
        description = "Generates iosApp/Configuration/iosConfig.xcconfig from module ios declarations."
        enabled = isMac
        outputs.file(outputFile)
        doLast {
            syncConfig()
        }
    }
}

private fun String.toXcconfigValue(): String = replace("\\", "\\\\").replace("\n", "\\n")
