package com.frame.basic.plugin

import org.gradle.api.Plugin
import org.gradle.api.Project
import org.gradle.nativeplatform.platform.internal.DefaultNativePlatform

/**
 * @Description: 聚合各 SDK 模块声明的 iOS 配置，生成给 Xcode Info.plist 使用的 xcconfig 文件。
 * @Author:         范俊
 * @CreateDate:     2026/07/03 11:56
 */
class PlistConfigPlugin : Plugin<Project> {
    override fun apply(target: Project) {
        val extension = target.extensions.create("plistConfig", PlistConfigExtension::class.java)
        val registry = target.rootProject.plistConfigRegistry()
        registry.add(target.path, extension)
        target.rootProject.configurePlistConfigTask(registry)

        target.tasks.register("generatePlistConfig") {
            group = "ios"
            description = "Generates SDKKeyConfig.xcconfig from all module plistConfig declarations."
            dependsOn(target.rootProject.tasks.named(PLIST_CONFIG_TASK_NAME))
        }
    }
}

open class PlistConfigExtension {
    private val fields = linkedMapOf<String, String>()

    fun field(name: String, value: String) {
        fields[name] = value
    }

    internal fun entries(): Map<String, String> = fields.toMap()
}

private const val PLIST_CONFIG_TASK_NAME = "generatePlistConfig"
private const val PLIST_CONFIG_EXTENSION_NAME = "plistConfigRegistry"
private val isMac = DefaultNativePlatform.getCurrentOperatingSystem().isMacOsX

private open class PlistConfigRegistry {
    private val extensions = linkedMapOf<String, PlistConfigExtension>()

    fun add(modulePath: String, extension: PlistConfigExtension) {
        extensions[modulePath] = extension
    }

    fun toXcconfigContent(): String {
        val fields = linkedMapOf<String, Pair<String, String>>()
        extensions.forEach { (modulePath, extension) ->
            extension.entries().forEach { (name, value) ->
                val previous = fields.put(name, modulePath to value)
                require(previous == null || previous.second == value) {
                    "Duplicate iOS plist key '$name' from ${previous?.first} and $modulePath."
                }
            }
        }

        return buildString {
            appendLine("// This file is automatically generated by Gradle. Do not edit manually.")
            fields.forEach { (name, moduleAndValue) ->
                appendLine("$name=${moduleAndValue.second.toXcconfigValue()}")
            }
        }
    }
}

private fun Project.plistConfigRegistry(): PlistConfigRegistry {
    val existing = extensions.findByName(PLIST_CONFIG_EXTENSION_NAME) as? PlistConfigRegistry
    if (existing != null) return existing
    return extensions.create(PLIST_CONFIG_EXTENSION_NAME, PlistConfigRegistry::class.java)
}

private fun Project.configurePlistConfigTask(registry: PlistConfigRegistry) {
    if (tasks.findByName(PLIST_CONFIG_TASK_NAME) != null) return

    val outputFile = file("iosApp/Configuration/SDKKeyConfig.xcconfig")
    fun syncConfig() {
        val newContent = registry.toXcconfigContent()
        if (!outputFile.exists() || outputFile.readText() != newContent) {
            outputFile.parentFile.mkdirs()
            outputFile.writeText(newContent)
            logger.lifecycle("${outputFile.name} updated successfully from plistConfig declarations")
        }
    }

    if (isMac) {
        gradle.projectsEvaluated {
            syncConfig()
        }
    }

    tasks.register(PLIST_CONFIG_TASK_NAME) {
        group = "ios"
        description = "Generates iosApp/Configuration/SDKKeyConfig.xcconfig from module plist declarations."
        enabled = isMac
        outputs.file(outputFile)
        doLast {
            syncConfig()
        }
    }
}

private fun String.toXcconfigValue(): String = replace("\\", "\\\\").replace("\n", "\\n")
